// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'evently';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String ICON_DATE = 'assets/icons/icon_date.png';
  static const String ICON_EDIT = 'assets/icons/icon_edit.png';
  static const String ICON_EMAIL = 'assets/icons/icon_email.png';
  static const String ICON_GOOGLE = 'assets/icons/icon_google.png';
  static const String ICON_LOCATION = 'assets/icons/icon_location.png';
  static const String ICON_LOCK = 'assets/icons/icon_lock.png';
  static const String ICON_NAME = 'assets/icons/icon_name.png';
  static const String ICON_PASSWORD = 'assets/icons/icon_password.png';
  static const String ICON_SHOW_PASSWORD = 'assets/icons/icon_show_password.png';
  static const String ICON_TIME = 'assets/icons/icon_time.png';
  static const String LOGO_TOP = 'assets/icons/logo_top.png';
  static const String BOOK_CLUB_IMAGE = 'assets/images/book_club_image.png';
  static const String EATING_IMAGE = 'assets/images/eating_image.png';
  static const String EXHIBITION_IMAGE = 'assets/images/exhibition_image.png';
  static const String GAMING_IMAGE = 'assets/images/gaming_image.png';
  static const String HOLIDAY_IMAGE = 'assets/images/holiday_image.png';
  static const String MEETING_IMAGE = 'assets/images/meeting_image.png';
  static const String SPORT_IMAGE = 'assets/images/sport_image.png';
}
